### ISSUE TITLE
dismiss the view by clicking

### ISSUE THREAD

**Issue by mitchhankins01** [tolgaarikan/CountdownView#1]
I absolutely LOVE this library, awesome job!

I have it all set up but I would like to be able to dismiss it by pressing anywhere on the screen, or maybe adding an X button. Is this possible?

Thanks!

**Comment by tolgahan-arikan** [comment]
Thank you very much for the kind words.

Yeah sure, I think dismissing by pressing anywhere on the screen will be a good addition.
I will do this tomorrow and update the pod.

**Comment by mitchhankins01** [comment]
You rock man! Seriously saved me a lot of trouble with this awesome library. 

I think being able to choose whether you want to dismiss by 
- tapping anywhere on the screen or
- tapping on a X symbol

The latter would be good so the user doesn't accidentally hit the screen. Just an idea!

**Comment by tolgahan-arikan** [comment]
Would you prefer dismissing the counter after the counting finishes and the timer shows '0' or while the counter is counting?

**Comment by mitchhankins01** [comment]
I would prefer while it is counting, because I implement it in a workout app. Do it counts down for rest, sometimes you don't want to rest but move to the new exercise. 

Thanks for taking a request so detailed. I'd like to PayPal you to buy some coffee if you have it!

**Comment by mitchhankins01** [comment]
Do = so

**Comment by tolgahan-arikan** [comment]
Oh I see. Makes sense. Thank you for the thought but I can't use Paypal since I live in Turkey and your interest in the project is enough for me 👍

**Comment by mitchhankins01** [comment]
Awesome :) also id like to make another suggestion. It'd also be cool to change the colors. A black background with white text for example would look really cool. Just thought I'd mention it

**Comment by tolgahan-arikan** [comment]
Sure, the api is already public but I didn't have time to write a proper README, I will update the README file with the changes.

**Comment by mitchhankins01** [comment]
Hi @tolgaarikan 
Just wanted to let you know I just updated to the new version

I cannot dismiss the timer; but there might be a bigger problem. When the timer ends, the program crashes with a "fatal error: unexpectedly found nil while unwrapping an Optional value" error.

The problem seems to be in CountdownView.swift at line 286

I am calling the function as:

`CountdownView.show(countdownFrom: programExerciseRest, spin: true, animation: CountdownView.Animation.zoomIn, autoHide: true, completion: nil)`

**Comment by tolgahan-arikan** [comment]
Hi @IronCoderXYZ,
I will update the README today about the new changes, but for now you can see the example project to find out how to use dismissing.
Thank you for bug report. I didn't have much time to test it out. I will be fixing that today as well.

**Comment by tolgahan-arikan** [comment]
Hi @IronCoderXYZ,

If you don't have any problems I will close the issue.
